# Server
server:
  port: 8080
# JWT
jwt:
  secret: oVT3Hf4kzYuzrJBc1IZxNwD1f611IlWDBlU1QKF/H2s=
  accessTokenExpirationMs: 900000        # 15 minutes
  refreshTokenExpirationMs: 604800000 # 7 days
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
# CORS
cors:
  allowedOrigins: http://localhost:4200,http://localhost:4201
